### ISSUE TITLE
Balance: 0.0 USDT

### ISSUE THREAD

**Issue by Matk73** [CryptoRobotFr/Live-Tools-V2#11]
Bonjour,
J'ai placé l'équivalent de 0.007 BTC sur bidget en spot et j'ai configuré l'api-key dans secret.py:
![image](https://github.com/CryptoRobotFr/Live-Tools-V2/assets/171506691/56e2c921-1aea-45c8-affb-66f4798315b2)

Cependant, je lance le programme et le get_balance() me retourn 0.0 USDT, du coup la suite du programme plante car inférieur à 0.001:

--- Execution started at 2024-06-09 17:29:02 ---
Pair REN/USDT not found, removing from params...
Pair REEF/USDT not found, removing from params...
Setting isolated x3 on 20 pairs...
Getting data and indicators on 20 pairs...
Balance: 0.0 USDT
Getting open trigger orders...
Canceling trigger orders...
Getting open orders...
Canceling limit orders...
Getting live positions...
Placing 0 close SL / limit order...
Placing 156 open limit order...
Error limit buy 0 BTC/USDT:USDT - Trigger 64948.3 - Price 64625.1 - Error => bitget amount of BTC/USDT:USDT must be greater than minimum amount precision of 0.001

Merci

**Comment by HyldenGit** [comment]
Salut
Il te faut un solde positif en USDT sur ton compte spot.Il faut que tu convertisses tes btc en usdt.

Yahoo Mail : Recherchez, organisez, maîtrisez 
 
  Le dim., juin 9, 2024 à 19:50, ***@***.***> a écrit:   


Bonjour,
J'ai placé l'équivalent de 0.007 BTC sur bidget en spot et j'ai configuré l'api-key dans secret.py:
image.png (view on web)

Cependant, je lance le programme et le get_balance() me retourn 0.0 USDT, du coup la suite du programme plante car inférieur à 0.001:

--- Execution started at 2024-06-09 17:29:02 ---
Pair REN/USDT not found, removing from params...
Pair REEF/USDT not found, removing from params...
Setting isolated x3 on 20 pairs...
Getting data and indicators on 20 pairs...
Balance: 0.0 USDT
Getting open trigger orders...
Canceling trigger orders...
Getting open orders...
Canceling limit orders...
Getting live positions...
Placing 0 close SL / limit order...
Placing 156 open limit order...
Error limit buy 0 BTC/USDT:USDT - Trigger 64948.3 - Price 64625.1 - Error => bitget amount of BTC/USDT:USDT must be greater than minimum amount precision of 0.001

Merci

**Comment by Matk73** [comment]
IBonjour merciPour ton retour,J'ai bien 500 USDT en spot mais il remonte 0 je ne dois pas avoir les 500 USDT en future ?Le 9 juin 2024 20:40, HyldenGit ***@***.***> a écrit :
Salut

Il te faut un solde positif en USDT sur ton compte spot.Il faut que tu convertisses tes btc en usdt.



Yahoo Mail : Recherchez, organisez, maîtrisez 

 

  Le dim., juin 9, 2024 à 19:50, ***@***.***> a écrit:   





Bonjour,

J'ai placé l'équivalent de 0.007 BTC sur bidget en spot et j'ai configuré l'api-key dans secret.py:

image.png (view on web)



Cependant, je lance le programme et le get_balance() me retourn 0.0 USDT, du coup la suite du programme plante car inférieur à 0.001:



--- Execution started at 2024-06-09 17:29:02 ---

Pair REN/USDT not found, removing from params...

Pair REEF/USDT not found, removing from params...

Setting isolated x3 on 20 pairs...

Getting data and indicators on 20 pairs...

Balance: 0.0 USDT

Getting open trigger orders...

Canceling trigger orders...

Getting open orders...

Canceling limit orders...

Getting live positions...

Placing 0 close SL / limit order...

Placing 156 open limit order...

Error limit buy 0 BTC/USDT:USDT - Trigger 64948.3 - Price 64625.1 - Error => bitget amount of BTC/USDT:USDT must be greater than minimum amount precision of 0.001



Merci

**Comment by HyldenGit** [comment]
Salut,
si si désolé, c'est bien sur le compte future que le solde doit être présent.

    Le lundi 10 juin 2024 à 09:40:01 UTC+2, Matk73 ***@***.***> a écrit :  
 
 

IBonjour merciPour ton retour,J'ai bien 500 USDT en spot mais il remonte 0 je ne dois pas avoir les 500 USDT en future ?Le 9 juin 2024 20:40, HyldenGit ***@***.***> a écrit :
Salut

Il te faut un solde positif en USDT sur ton compte spot.Il faut que tu convertisses tes btc en usdt.



Yahoo Mail : Recherchez, organisez, maîtrisez 

 

 Le dim., juin 9, 2024 à 19:50, ***@***.***> a écrit: 





Bonjour,

J'ai placé l'équivalent de 0.007 BTC sur bidget en spot et j'ai configuré l'api-key dans secret.py:

image.png (view on web)



Cependant, je lance le programme et le get_balance() me retourn 0.0 USDT, du coup la suite du programme plante car inférieur à 0.001:



--- Execution started at 2024-06-09 17:29:02 ---

Pair REN/USDT not found, removing from params...

Pair REEF/USDT not found, removing from params...

Setting isolated x3 on 20 pairs...

Getting data and indicators on 20 pairs...

Balance: 0.0 USDT

Getting open trigger orders...

Canceling trigger orders...

Getting open orders...

Canceling limit orders...

Getting live positions...

Placing 0 close SL / limit order...

Placing 156 open limit order...

Error limit buy 0 BTC/USDT:USDT - Trigger 64948.3 - Price 64625.1 - Error => bitget amount of BTC/USDT:USDT must be greater than minimum amount precision of 0.001



Merci

**Comment by TristanLeGoff** [comment]
Hello, alors c'est un bot Future donc il faut des USDT sur le compte Future USD-M, il te faut des USDT sur ton compte SPOT puis faire transfert entre ton compte SPOT et Future USDM
