### ISSUE TITLE
Error 22002  : No position to close

### ISSUE THREAD

**Issue by Trade2Million** [CryptoRobotFr/Live-Tools-V2#14]
J'ai un problème lorsque le script doit envoyer le SL et le TP, malgré une position ouverte on dirait qu'il ne la trouve pas.
Voici le message d'erreur en screens. Si vous avez une idée, merci.

![image](https://github.com/user-attachments/assets/c28ffb32-ca2c-4004-94ed-d21b2bd4be95)

![image](https://github.com/user-attachments/assets/d7370438-85fa-4baa-b1da-928fc6ae2814)

**Comment by TristanLeGoff** [comment]
Hello, le problème vient du fait que tu étais en mode de courverture (Hedge Mode) et dans ce cas il n'arrivait pas à faire le lien avec la position, je viens de commit un changement dans lequel maintenant le script à une variable hedge_mode au début et qui vient en paramètre dans le placement des ordres, il faut bien qu'elle soit à True dans ton cas

**Comment by Trade2Million** [comment]
Ok parfait, merci 👌
