### ISSUE TITLE
Erreur 45117 de Bitget : Currently holding positions or orders, the margin mode cannot be adjusted

### ISSUE THREAD

**Issue by wikitab** [CryptoRobotFr/Live-Tools-V2#2]
Hello,

J'ai une erreur lors de l'exécution :

Il y a eu une position prise sur MAGICUSDT mais sans stoploss.

--- Execution started at 2024-01-27 20:08:39 ---
Pair REN/USDT not found, removing from params...
Setting isolated x3 on 21 pairs...
Getting data and indicators on 21 pairs...
Balance: XXXXXXX USDT
Getting open trigger orders...
Canceling trigger orders...
Getting open orders...
Canceling limit orders...
Getting live positions...
Current position on MAGIC/USDT short - 162.8 ~ 184.71 $
Placing 2 close SL / limit order...
Traceback (most recent call last):
File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 443, in
asyncio.run(main())
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 439, in main
raise e
File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 381, in main
await asyncio.gather(*tasks_close) # Limit orders when in positions
File "/home/ubuntu/./Live-Tools-V2/utilities/bitget_perp.py", line 283, in place_order
raise e
File "/home/ubuntu/./Live-Tools-V2/utilities/bitget_perp.py", line 265, in place_order
resp = await self._session.create_order(
File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/bitget.py", line 3918, in create_order
response = await self.privateMixPostV2MixOrderPlaceOrder(request)
File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 759, in request
return await self.fetch2(path, api, method, params, headers, body, config)
File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 756, in fetch2
return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/bitget.py", line 7694, in handle_errors
raise ExchangeError(feedback) # unknown message
ccxt.base.errors.ExchangeError: bitget {"code":"45117","msg":"Currently holding positions or orders, the margin mode cannot be adjusted","requestTime":1706386168418,"data":null}

Auriez-vous une idée ??
Merci les gars ;-)

**Comment by michelflight** [comment]
idem chez moi

**Comment by michelflight** [comment]
en fait comme très souvent, les libs c'est bullshit, ici ccxt, c'est un vrai merdier, pourquoi s'en servir alors qu'on peut tout simplement utiliser directement les endpoints de bitget. Je vais tout recoder moi même.

**Comment by CryptoRobotFr** [comment]
Hello je n'ai pas de problème de mon côté donc je pense que c'est un soucis de version de ccxt. J'ai ajusté un peu le répertoire pour utiliser un environnement virtuel et éviter les soucis de ce type. Pour ce faire ce que je vous conseille c'est reprendre de zéro. Pour ça supprimer le dossier :
> sudo rm -r Live-Tools-V2/  

Puis retélécharger :
> git clone https://github.com/CryptoRobotFr/Live-Tools-V2.git  
> bash Live-Tools-V2/install.sh  

Pensez à bien remettre votre clé api et normalement cela devrait être bon. Pour tester :
>  bash Live-Tools-V2/1hcron.sh

**Comment by wikitab** [comment]
Hello,

Merci pour ta réponse.

Je suis reparti de zéro avec les fichiers modifiés sur GIT (avec les packages avec les bonnes version), mais j'ai encore la même erreur après avoir fait un short manuel de 0.01 ETH.

Je ne sais pas si ça a un impact, mais lors de l'install, j'ai un message sur la console SSH : voir la capture d'écran
![2024-01-29_20-19-49](https://github.com/CryptoRobotFr/Live-Tools-V2/assets/157920696/17b552a7-6084-46f4-8063-e1200bbb1bb6)


--- Execution started at 2024-01-29 19:32:54 ---
Pair REN/USDT not found, removing from params...
Setting isolated x3 on 21 pairs...
Getting data and indicators on 21 pairs...
Balance: XXXXXXXXXX USDT
Getting open trigger orders...
Canceling trigger orders...
Getting open orders...
Canceling limit orders...
Getting live positions...
Current position on ETH/USDT short - 0.01 ~ 23.0 $
Placing 2 close SL / limit order...
Traceback (most recent call last):
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 443, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 439, in main
    raise e
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 381, in main
    await asyncio.gather(*tasks_close)  # Limit orders when in positions
  File "/home/ubuntu/./Live-Tools-V2/utilities/bitget_perp.py", line 283, in place_order
    raise e
  File "/home/ubuntu/./Live-Tools-V2/utilities/bitget_perp.py", line 265, in place_order
    resp = await self._session.create_order(
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/bitget.py", line 3908, in create_order
    response = await self.privateMixPostV2MixOrderPlaceOrder(request)
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 753, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 750, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/bitget.py", line 7684, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bitget {"code":"45117","msg":"Currently holding positions or orders, the margin mode cannot be adjusted","requestTime":1706556823067,"data":null}
sys:1: RuntimeWarning: coroutine 'PerpBitget.place_trigger_order' was never awaited


A+ ;-)

**Comment by alexthenx** [comment]
Hello,

Exactement le même pb pour moi, j'ai tout essayé ccxt .20, .21, .22 et .23 et je viens une nouvelle fois de réinstaller le projet.

Les ordres ne se mettents plus dès que l'on a des positions ouvertes.

Voici la trace :

ubuntu@ip-172-31-46-97:~$ bash Live-Tools-V2/1hcron.sh
--- Execution started at 2024-01-31 13:45:48 ---
Setting crossed x4 on 22 pairs...
Getting data and indicators on 22 pairs...
Balance: 406.32 USDT
Getting open trigger orders...
Canceling trigger orders...
Getting open orders...
Canceling limit orders...
Getting live positions...
Current position on ROSE/USDT long - 207.0 ~ 21.03 $
Placing 2 close SL / limit order...
Traceback (most recent call last):
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 443, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 439, in main
    raise e
  File "/home/ubuntu/Live-Tools-V2/strategies/envelopes/multi_bitget.py", line 381, in main
    await asyncio.gather(*tasks_close)  # Limit orders when in positions
  File "/home/ubuntu/./Live-Tools-V2/utilities/bitget_perp.py", line 283, in place_order
    raise e
  File "/home/ubuntu/./Live-Tools-V2/utilities/bitget_perp.py", line 265, in place_order
    resp = await self._session.create_order(
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/bitget.py", line 3908, in create_order
    response = await self.privateMixPostV2MixOrderPlaceOrder(request)
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 753, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 750, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ubuntu/Live-Tools-V2/.venv/lib/python3.10/site-packages/ccxt/async_support/bitget.py", line 7684, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bitget {"code":"45117","msg":"Currently holding positions or orders, the margin mode cannot be adjusted","requestTime":1706705190338,"data":null}

Merci,

**Comment by alexthenx** [comment]
Re,

J'ai décommenté les lignes margin_mode dans les fonctions place_order et place_trigger_order et tout fonctionne maintenant : 


    async def place_order(
        self,
        pair,
        side,
        price,
        size,
        type="limit",
        reduce=False,
        margin_mode="crossed",
        error=True,
    ) -> Order:
        try:
            pair = self.ext_pair_to_pair(pair)
            trade_side = "Open" if reduce is False else "Close"
            resp = await self._session.create_order(
                symbol=pair,
                type=type,
                side=side,
                amount=size,
                price=price,
                params={
                    "reduceOnly": reduce,
                    "tradeSide": trade_side,
                    # "marginMode": margin_mode,
                },
            )
            order_id = resp["id"]
            pair = self.pair_to_ext_pair(resp["symbol"])
            order = await self.get_order_by_id(order_id, pair)
            return order
        except Exception as e:
            if error:
                raise e
            else:
                print(e)
                return None

    async def place_trigger_order(
        self,
        pair,
        side,
        price,
        trigger_price,
        size,
        type="limit",
        reduce=False,
        margin_mode="crossed",
        error=True,
    ) -> Info:
        try:
            pair = self.ext_pair_to_pair(pair)
            trade_side = "Open" if reduce is False else "Close"
            trigger_order = await self._session.create_trigger_order(
                symbol=pair,
                type=type,
                side=side,
                amount=size,
                price=price,
                triggerPrice=trigger_price,
                params={
                    "reduceOnly": reduce,
                    "tradeSide": trade_side,
                    # "marginMode": margin_mode,
                },
            )
            resp = Info(success=True, message="Trigger Order set up")
            return resp
        except Exception as e:
            if error:
                raise e
            else:
                print(e)
                return None

Voici la dernière trace : 

--- Execution started at 2024-01-31 13:56:36 ---
Setting crossed x4 on 22 pairs...
Getting data and indicators on 22 pairs...
Balance: 406.25 USDT
Getting open trigger orders...
Canceling trigger orders...
Getting open orders...
Canceling limit orders...
Getting live positions...
Current position on ROSE/USDT long - 207.0 ~ 20.99 $
Placing 2 close SL / limit order...
Placing 202 open limit order...
--- Execution finished at 2024-01-31 13:58:02 ---

@CryptoRobotFr peux-tu nous confirmer si c'était bien ça le pb ?

Merci beaucoup,

Alexandre.

**Comment by alexthenx** [comment]
Hello,

Pour info j'ai les deux scripts sur deux comptes (un en crossed et l'autre en isolated) --> l'erreur margin mode lorsqu'une position est ouverte ne se produit que sur les positions crossed. Il n'y a aucune erreur avec mon autre script qui est sur des positions isolated.

**Comment by baribalfb** [comment]
> Re,
> 
> J'ai décommenté les lignes margin_mode dans les fonctions place_order et place_trigger_order et tout fonctionne maintenant :
> 
> ```
> async def place_order(
>     self,
>     pair,
>     side,
>     price,
>     size,
>     type="limit",
>     reduce=False,
>     margin_mode="crossed",
>     error=True,
> ) -> Order:
>     try:
>         pair = self.ext_pair_to_pair(pair)
>         trade_side = "Open" if reduce is False else "Close"
>         resp = await self._session.create_order(
>             symbol=pair,
>             type=type,
>             side=side,
>             amount=size,
>             price=price,
>             params={
>                 "reduceOnly": reduce,
>                 "tradeSide": trade_side,
>                 # "marginMode": margin_mode,
>             },
>         )
>         order_id = resp["id"]
>         pair = self.pair_to_ext_pair(resp["symbol"])
>         order = await self.get_order_by_id(order_id, pair)
>         return order
>     except Exception as e:
>         if error:
>             raise e
>         else:
>             print(e)
>             return None
> 
> async def place_trigger_order(
>     self,
>     pair,
>     side,
>     price,
>     trigger_price,
>     size,
>     type="limit",
>     reduce=False,
>     margin_mode="crossed",
>     error=True,
> ) -> Info:
>     try:
>         pair = self.ext_pair_to_pair(pair)
>         trade_side = "Open" if reduce is False else "Close"
>         trigger_order = await self._session.create_trigger_order(
>             symbol=pair,
>             type=type,
>             side=side,
>             amount=size,
>             price=price,
>             triggerPrice=trigger_price,
>             params={
>                 "reduceOnly": reduce,
>                 "tradeSide": trade_side,
>                 # "marginMode": margin_mode,
>             },
>         )
>         resp = Info(success=True, message="Trigger Order set up")
>         return resp
>     except Exception as e:
>         if error:
>             raise e
>         else:
>             print(e)
>             return None
> ```
> 
> Voici la dernière trace :
> 
> --- Execution started at 2024-01-31 13:56:36 --- Setting crossed x4 on 22 pairs... Getting data and indicators on 22 pairs... Balance: 406.25 USDT Getting open trigger orders... Canceling trigger orders... Getting open orders... Canceling limit orders... Getting live positions... Current position on ROSE/USDT long - 207.0 ~ 20.99 $ Placing 2 close SL / limit order... Placing 202 open limit order... --- Execution finished at 2024-01-31 13:58:02 ---
> 
> @CryptoRobotFr peux-tu nous confirmer si c'était bien ça le pb ?
> 
> Merci beaucoup,
> 
> Alexandre.

Je confirme.
C'est dans le fichier "Live-Tools-V2/utilities/bitget_perp.py" qu'il faut apporter la modification.
